[package]
name = "sender"
version = "0.1.0"
edition = "2021"

[dependencies]
sysinfo = "0.29.10"

[dependencies.windows]
version = "0.51"
features = [
    "Win32_Foundation",
    "Win32_System_Console",
]
